/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppVehiclesRouteImport } from './routes/_app/vehicles'
import { Route as AppRequestsIndexRouteImport } from './routes/_app/requests.index'
import { Route as AppRequestsRequestIdRouteImport } from './routes/_app/requests.$requestId'
import { Route as AppRequestsNewRouteImport } from './routes/_app/requests.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRequestsRoute,
} as any)
const AppRequestsRequestIdRoute = AppRequestsRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => AppRequestsRoute,
} as any)
const AppRequestsNewRoute = AppRequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRequestsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/inventory': typeof AppInventoryRoute
  '/reports': typeof AppReportsRoute
  '/requests': typeof AppRequestsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/vehicles': typeof AppVehiclesRoute
  '/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/requests/new': typeof AppRequestsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/requests/': typeof AppRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/inventory': typeof AppInventoryRoute
  '/reports': typeof AppReportsRoute
  '/users': typeof AppUsersRoute
  '/vehicles': typeof AppVehiclesRoute
  '/': typeof AppIndexRoute
  '/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/requests/new': typeof AppRequestsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/requests': typeof AppRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/requests': typeof AppRequestsRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/_app/vehicles': typeof AppVehiclesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/_app/requests/new': typeof AppRequestsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/requests/': typeof AppRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/inventory'
    | '/reports'
    | '/requests'
    | '/users'
    | '/vehicles'
    | '/requests/$requestId'
    | '/requests/new'
    | '/api/auth/$'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/inventory'
    | '/reports'
    | '/users'
    | '/vehicles'
    | '/'
    | '/requests/$requestId'
    | '/requests/new'
    | '/api/auth/$'
    | '/requests'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/inventory'
    | '/_app/reports'
    | '/_app/requests'
    | '/_app/users'
    | '/_app/vehicles'
    | '/_app/'
    | '/_app/requests/$requestId'
    | '/_app/requests/new'
    | '/api/auth/$'
    | '/_app/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/': {
      id: '/_app/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRequestsRoute
    }
    '/_app/requests/$requestId': {
      id: '/_app/requests/$requestId'
      path: '/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AppRequestsRequestIdRouteImport
      parentRoute: typeof AppRequestsRoute
    }
    '/_app/requests/new': {
      id: '/_app/requests/new'
      path: '/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AppRequestsNewRouteImport
      parentRoute: typeof AppRequestsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRequestsRouteChildren {
  AppRequestsRequestIdRoute: typeof AppRequestsRequestIdRoute
  AppRequestsNewRoute: typeof AppRequestsNewRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
}

const AppRequestsRouteChildren: AppRequestsRouteChildren = {
  AppRequestsRequestIdRoute: AppRequestsRequestIdRoute,
  AppRequestsNewRoute: AppRequestsNewRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
}

const AppRequestsRouteWithChildren = AppRequestsRoute._addFileChildren(
  AppRequestsRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRequestsRoute: typeof AppRequestsRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppReportsRoute: AppReportsRoute,
  AppRequestsRoute: AppRequestsRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
